{{- if and (not .ephemeral) (not .headless) }}
{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}/MesloLGS NF Regular.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Bold.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Bold Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Regular.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Regular.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Italic.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Italic.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Mono Regular.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Mono Regular.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Mono Italic.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia Cove Nerd Font Complete Mono Italic.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Bold.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Bold/complete/Caskaydia Cove Nerd Font Complete Bold.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Bold Italic.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Bold/complete/Caskaydia Cove Nerd Font Complete Bold Italic.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Mono Bold.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Bold/complete/Caskaydia Cove Nerd Font Complete Mono Bold.otf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Caskaydia Cove Nerd Font Complete Mono Bold Italic.otf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Bold/complete/Caskaydia Cove Nerd Font Complete Mono Bold Italic.otf"
    refreshPeriod = "168h"
{{-   if (eq .chezmoi.osRelease.id "fedora") }}
[".local/bin/gnome-shell-extension-installer"]
    type = "file"
    url = "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    refreshPeriod = "168h"
    executable = true
{{-   end }}
{{- end }}
